### Generated by Winemaker 0.8.4
###
### Invocation command line was
### /usr/bin/winemaker .


SRCDIR                = .
SUBDIRS               =
DLLS                  =
LIBS                  =
EXES                  = test.exe



### Common settings

CEXTRA                = -g -isystem /usr/include/wine-development/windows -m32 -mno-cygwin
CXXEXTRA              =
RCEXTRA               =
DEFINES               =
INCLUDE_PATH          =
DLL_PATH              =
DLL_IMPORTS           =
LIBRARY_PATH          =
LIBRARIES             =


### test.exe sources and settings

test_exe_MODULE       = test.exe
test_exe_C_SRCS       = test.c
test_exe_CXX_SRCS     =
test_exe_RC_SRCS      =
test_exe_LDFLAGS      = -m32 -mwindows \
			-mno-cygwin
test_exe_ARFLAGS      =
test_exe_DLL_PATH     =
test_exe_DLLS         = odbc32 \
			ole32 \
			oleaut32 \
			winspool \
			odbccp32
test_exe_LIBRARY_PATH =
test_exe_LIBRARIES    = uuid

test_exe_OBJS         = $(test_exe_C_SRCS:.c=.o) \
			$(test_exe_CXX_SRCS:.cpp=.o) \
			$(test_exe_RC_SRCS:.rc=.res)



### Global source lists

C_SRCS                = $(test_exe_C_SRCS)
CXX_SRCS              = $(test_exe_CXX_SRCS)
RC_SRCS               = $(test_exe_RC_SRCS)


### Tools

CC = winegcc-development
CXX = wineg++
RC = wrc
AR = ar


### Generic targets

all: $(SUBDIRS) $(DLLS:%=%.so) $(LIBS) $(EXES)

### Build rules

.PHONY: all clean dummy

$(SUBDIRS): dummy
	@cd $@ && $(MAKE)

# Implicit rules

.SUFFIXES: .cpp .cxx .rc .res
DEFINCL = $(INCLUDE_PATH) $(DEFINES) $(OPTIONS)

.c.o:
	$(CC) -c $(CFLAGS) $(CEXTRA) $(DEFINCL) -o $@ $<

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(CXXEXTRA) $(DEFINCL) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(CXXEXTRA) $(DEFINCL) -o $@ $<

.rc.res:
	$(RC) $(RCFLAGS) $(RCEXTRA) $(DEFINCL) -fo$@ $<

# Rules for cleaning

CLEAN_FILES     = y.tab.c y.tab.h lex.yy.c core *.orig *.rej \
                  \\\#*\\\# *~ *% .\\\#*

clean:: $(SUBDIRS:%=%/__clean__) $(EXTRASUBDIRS:%=%/__clean__)
	$(RM) $(CLEAN_FILES) $(RC_SRCS:.rc=.res) $(C_SRCS:.c=.o) $(CXX_SRCS:.cpp=.o)
	$(RM) $(DLLS:%=%.so) $(LIBS) $(EXES) $(EXES:%=%.so)

$(SUBDIRS:%=%/__clean__): dummy
	cd `dirname $@` && $(MAKE) clean

$(EXTRASUBDIRS:%=%/__clean__): dummy
	-cd `dirname $@` && $(RM) $(CLEAN_FILES)

### Target specific build rules
DEFLIB = $(LIBRARY_PATH) $(LIBRARIES) $(DLL_PATH) $(DLL_IMPORTS:%=-l%)

$(test_exe_MODULE): $(test_exe_OBJS)
	$(CC) $(test_exe_LDFLAGS) -o $@ $(test_exe_OBJS) $(test_exe_LIBRARY_PATH) $(test_exe_DLL_PATH) $(DEFLIB) $(test_exe_DLLS:%=-l%) $(test_exe_LIBRARIES:%=-l%)


